### PR TITLE
Updated App Engine Sidekiq + Rails tutorial to work with split health checks

### PR DESCRIPTION
**Pull request by MoHayat**
Hello -- I opened an issue a few days ago regarding the sidekiq tutorial being outdated and thought I'd submit the fixes that I made to get my background worker instance running and passing the health checks.

Specifically, here's what I changed with the tutorial:

1. instructed users to save or copy password used for Redis instance and add it as an environment variable in `app.yaml` and `worker.yaml`, since the linked guide states that setting up a password is important to protecting the instance.
2. in Option B of the deployments, added instructions to install and configure the `sidekiq_alive` gem to make the background worker instance pass the health checks. I also replaced the `health_check` attribute with `liveness_check` and `readiness_check` configurations, since health checks have been phased out
3. added my github username in authors section to be tagged in case any future users had questions regarding my approach (am I allowed to do this?).

### CODE REVIEW

**Comment by MoHayat** [comment]
@googlebot I signed it!

**Comment by ToddKopriva** [comment]
Thanks for the fix. We'll review it soon.

**Comment by ToddKopriva** [comment]
@chingor13 , could you have a look at this suggested fix for a document that you contributed?

**Comment by ToddKopriva** [comment]
For reference, here is the issue report:
https://github.com/GoogleCloudPlatform/community/issues/1529

**Review by chingor13 — APPROVED** [review]
LGTM, but I haven't worked with GAE flexible environment in quite some time.

**Comment by ToddKopriva** [comment]
Thanks for the review, @chingor13 .

I'll do an editorial review and then merge the fix.

**Review by shivamkumar0611 — APPROVED** [review]

**Review by shivamkumar0611 — APPROVED** [review]

**Review by shivamkumar0611 — APPROVED** [review]

**Review by ToddKopriva — APPROVED** [review]

**Comment by ToddKopriva** [comment]
Thanks for the fix, @MoHayat .

I'll publish these changes within a couple of days.

**Comment by MoHayat** [comment]
Sounds great, I appreciate all the help!

**Pull request merged**
