### PR TITLE
Added Eventarc and Workflows integration tutorial

### PR DESCRIPTION
**Pull request by meteatamel**

### CODE REVIEW

**Comment by meteatamel** [comment]
@ToddKopriva Could you please review or direct me someone who can?

**Comment by meteatamel** [comment]
Hi @ToddKopriva, any ETA for the review & merge? I'm waiting to publish a blog post around this and it'd be useful to know the timeline.

**Comment by ToddKopriva** [comment]
> Hi @ToddKopriva, any ETA for the review & merge? I'm waiting to publish a blog post around this and it'd be useful to know the timeline.

Late this week.

**Comment by meteatamel** [comment]
Thanks. I actually decided to host the code of this tutorial in a different repo, so I can update it quicker. I'll update the PR shortly to reflect that.

**Comment by meteatamel** [comment]
I moved the source code to a different repo and made the tutorial to simply refer to that repo.

**Comment by meteatamel** [comment]
@ToddKopriva Any update?

**Comment by ToddKopriva** [comment]
This will be reviewed and merged this week.

**Review by ToddKopriva — APPROVED** [review]

**Comment by ToddKopriva** [comment]
This will be published on cloud.google.com on Monday.

**Comment by ToddKopriva** [comment]
published:
https://cloud.google.com/community/tutorials/eventarc-workflows-integration

**Comment by meteatamel** [comment]
Thanks

**Pull request merged**
