### PR TITLE
The button says "CREATE INSTANCE", not just "CREATE"

### PR DESCRIPTION
**Pull request by zabop**
"CREATE INSTANCE" button on the top:
image

### CODE REVIEW

**Review by ToddKopriva — APPROVED** [review]

**Comment by ToddKopriva** [comment]
Thanks for the fix, @zabop .

We just need you to sign the CLA so that we can accept the submission.

**Comment by zabop** [comment]
Your welcome! I tried signing the CLA, if I click on the [link](https://cla.developers.google.com/clas) it says "It looks like you've already signed this CLA". I don't think I'm using any other email address than my usual one.

**Comment by zabop** [comment]
@googlebot I signed it!

**Comment by zabop** [comment]
Oh ok, this seems to have solved it :)

**Comment by ToddKopriva** [comment]
Thanks again.

**Pull request merged**
