### PR TITLE
Allowing third party services to access specific backend resources in a Shared VPC

### PR DESCRIPTION
**Pull request by skalolazka**
Hi! This is a tutorial with Terraform code in the tutorials/serverless-backend-access-in-shared-vpc folder.

### CODE REVIEW

**Review by ToddKopriva — APPROVED** [review]

**Comment by ToddKopriva** [comment]
Thanks for the document, @skalolazka .

I've given it a thorough edit and production pass and merged it. The document will be published on cloud.google.com on Monday.

**Comment by skalolazka** [comment]
Thank you so much!

**Comment by nplanner** [comment]
Thank you Todd

**Comment by ToddKopriva** [comment]
published:
https://cloud.google.com/community/tutorials/serverless-backend-access-in-shared-vpc

**Pull request merged**
