### PR TITLE
Create index.md

### PR DESCRIPTION
**Pull request by carmel99**
Creating Strongswan VPN guide.

### CODE REVIEW

**Comment by epluscloudservices** [comment]
The CLA was signed today!

**Comment by epluscloudservices** [comment]
The check for cla/google is still showing `Required`. What am I doing wrong?

**Comment by ToddKopriva** [comment]
@carmel99 , you'll need to sign the CLA for this PR to continue. See the comment from the googlebot near the top of this comment thread for details.

**Comment by ashishverm** [comment]
This is now a duplicate of https://github.com/GoogleCloudPlatform/community/pull/672 so we can close this out.

**Comment by ToddKopriva** [comment]
Thanks, @ashishverm . I'll close this, and we can focus on the newer version in #672 .

**Pull request closed without merging**
