### PR TITLE
Using flask-login extension with Firestore in Datastore mode

### PR DESCRIPTION
**Pull request by komlasapaty**
Using Firestore in Datastore mode as the database backend for Flask-Login extension.
This tutorial shows how to represent your entity as a Python class to satisfy the requirement for packages like Flask-Login.

### CODE REVIEW

**Comment by ToddKopriva** [comment]
Thanks for the contribution. There are a few other items in the queue ahead of this, so I will probably do my review on Tuesday of this week.

**Comment by komlasapaty** [comment]
> Thanks for the contribution. There are a few other items in the queue ahead of this, so I will probably do my review on Tuesday of this week.

@ToddKopriva Thanks. I'm on standby.

**Comment by komlasapaty** [comment]
Hi @ToddKopriva , any feedback on this submission?

**Comment by ToddKopriva** [comment]
Sorry for the delay. I'll review it soon.

**Comment by komlasapaty** [comment]
Okay, Todd.

**Review by ToddKopriva — APPROVED** [review]

**Comment by ToddKopriva** [comment]
Thanks again for the contribution. I'll publish this with the next batch, either tomorrow or Monday.

**Comment by ToddKopriva** [comment]
https://cloud.google.com/community/tutorials/using-flask-login-with-cloud-datastore

**Comment by komlasapaty** [comment]
Thanks!

**Comment by ToddKopriva** [comment]
Thank _you_.

**Pull request merged**
