### PR TITLE
Updated cloud-iot-logging tutorial issues

### PR DESCRIPTION
**Pull request by jos-**
- Upgraded some dependencies
- Updated code for latest version of sdk
- Linter fixes
- Renamed Stackdriver to Cloud Logging

### CODE REVIEW

**Comment by ToddKopriva** [comment]
Thanks for the fixes, @jos- . 

@ptone , could you have a look at these fixes for some code that you submitted?

**Review by munkhuushmgl — APPROVED** [review]

**Review by gguuss — APPROVED** [review]
LGTM.

**Comment by gguuss** [comment]
We'll just need the CLA check and this should be good to go :)

**Comment by ToddKopriva** [comment]
@jos- , as @gguuss says, we just need you to follow the google-cla bot's instructions to sign the CLA.

Thanks again for the fixes.

**Review by ToddKopriva — APPROVED** [review]

**Comment by ToddKopriva** [comment]
@jos- , we're ready to merge this pull request if you accept the contributor license agreement.

Let us know whether you want to move forward with this pull request.

**Comment by gguuss** [comment]
@jos- Friendly ping to sign the CLA.

**Comment by jos-** [comment]
@googlebot I signed it!

**Review by ToddKopriva — APPROVED** [review]

**Comment by ToddKopriva** [comment]
Thanks, @jos- .

**Pull request merged**
