### PR TITLE
Community Tutorial: Dataform and ELT Orchestration

### PR DESCRIPTION
**Pull request by slachterman-g**
PR to publish blog on ELT Orchestration using Dataform to Community Tutorials

### CODE REVIEW

**Comment by ToddKopriva** [comment]
Thanks for the contribution. 

There are a few other items in the review queue, so we'll have a look at this early next week. 

In the meantime, it seems that the linter is complaining about the frontmatter. At a glance, I can see that you're missing an estimated date published. You can fill any date in there; I'll update it when we actually merge the PR.

**Comment by ToddKopriva** [comment]
Thanks for fixing the frontmatter issues, @slachterman-g . I'll get to this review ASAP.

**Comment by ToddKopriva** [comment]
I'll publish this to cloud.google.com with a batch of updates tomorrow.

**Comment by slachterman-g** [comment]
Thanks Todd.

Sam Lachterman

Customer Engineering Manager

(212) 565-6790‬

**Pull request merged**
