### PR TITLE
Deploying a private Godoc server on Kubernetes

### PR DESCRIPTION
**Pull request by richarddli**
This tutorial shows how to deploy a simple private Godoc server on Kubernetes. Feedback welcome!

### CODE REVIEW

**Comment by ToddKopriva** [comment]
Thanks for the submission, @richarddli . There are a few other items in the queue, so it may be a couple of days before this gets reviewed.

**Comment by richarddli** [comment]
No problem, thank you @ToddKopriva!

**Comment by richarddli** [comment]
@ToddKopriva Just wanted to check to see if you had any feedback? Thanks!

**Comment by ToddKopriva** [comment]
I'll be reviewing this today or tomorrow.

**Comment by ToddKopriva** [comment]
Thanks again for the tutorial, @richarddli . I'll publish this to cloud.google.com/community on Monday.

**Comment by richarddli** [comment]
Thank you!

**Pull request merged**
