### PR TITLE
docs: fix broken links and outdated sqlalchemy blurb

### PR DESCRIPTION
**Pull request by cpcloud**
This PR fixes broken links and outdated prose.

### CODE REVIEW

**Comment by cpcloud** [comment]
@tswast Mind having a look?

**Review by tswast — APPROVED** [review]
Looks great! Thanks for the fix.

**Comment by tswast** [comment]
@ToddKopriva Not sure if there's anything you'd want to take a look at before we merge this.

**Review by ToddKopriva — APPROVED** [review]

**Comment by ToddKopriva** [comment]
Thanks for the fix, @cpcloud .

**Pull request merged**
