### PR TITLE
Create index.md

### PR DESCRIPTION
**Pull request by epluscloudservices**
This is a new publish request that will hopefully get past the prior CLA issues with the epluscloudservces account having privacy settings enabled. The epluscloudservices account is now public. Let's hope for the best!

### CODE REVIEW

**Comment by ToddKopriva** [comment]
Hooray for the CLA!

Let me get Peter to verify the editorial review for this PR, since he was the original reviewer on this.

**Comment by ToddKopriva** [comment]
- [] editorial review: @PTDelaney 
 - [] final production review for publishing: @ToddKopriva

**Comment by ToddKopriva** [comment]
I added a period to the description to satisfy the picky CLI test.

**Comment by PTDelaney** [comment]
Thanks, Todd!

**Comment by ToddKopriva** [comment]
I still need to do the production pass, which at the very least includes updating the image reference.

**Pull request merged**
