### PR TITLE
feat!(GAE PHP): php72 -> php in GAE paths

### PR DESCRIPTION
**Pull request by ace-n**

### CODE REVIEW

**Review by ToddKopriva — COMMENTED** [review]
I just tested the new links, and I get 404s.

**Comment by ace-n** [comment]
@ToddKopriva forgot to mention - this depends on [this PR](https://github.com/GoogleCloudPlatform/php-docs-samples/pull/1270).

**Comment by ToddKopriva** [comment]
Got it. If you update here when the upstream PR is merged, we can merge this one immediately after that.

**Comment by ace-n** [comment]
@ToddKopriva would you or @bshaffer mind pre-approving?

(That way I don't need to ping y'all to merge everything in one go.)

**Review by ToddKopriva — APPROVED** [review]
approving, contingent on upstream pull request mentioned in comments

**Comment by ace-n** [comment]
@bshaffer asked us to move from `appengine/php` to `appengine/standard`. Updated this PR accordingly.

**Review by bshaffer — APPROVED** [review]

**Comment by ToddKopriva** [comment]
Thanks again for the fix. I'll republish the document to pick up the changes tomorrow.

**Pull request merged**
