### PR TITLE
Batch tokenize detokenize

### PR DESCRIPTION
**Pull request by arunsingh2803**
Added example for batch tokenize and detokenize usecase. Updated Readme file with instructions.

### CODE REVIEW

**Comment by arunsingh2803** [comment]
@ianmaddox @ToddKopriva any update on this?

**Comment by ToddKopriva** [comment]
> @ianmaddox @ToddKopriva any update on this?

We will review this after dealing with other items in our queues.

**Comment by anantdamle** [comment]
@arunsingh2803 have you reviewed batch tokenize  csv [solution](https://github.com/GoogleCloudPlatform/auto-data-tokenize)  ? Do you think it covers this use case?

**Comment by arunsingh2803** [comment]
@anantdamle as discussed with you this example script is for simpler use case where user just want to use an API from UI which can tokenize/detokenize data from csv file

**Review by ianmaddox — APPROVED** [review]

**Comment by ianmaddox** [comment]
LGTM

**Review by ToddKopriva — APPROVED** [review]

**Pull request merged**
