### PR TITLE
Add Google Cloud Run / Cloudflare tutorial

### PR DESCRIPTION
**Pull request by eblaauw**

### CODE REVIEW

**Comment by eblaauw** [comment]
@googlebot I signed it!

**Comment by eblaauw** [comment]
Hi @ToddKopriva, hope you are well. I am getting the following test errror:

``` AssertionError [ERR_ASSERTION]: description should be of the form /^[a-zA-Z0-9\s.,\-()&#'"\/!]+\.$/. ``` but I do not see how my description does not match. Would you mind helping me out?

If you prefer to talk about this on email, we have a dedicated TAM for Delivery Hero, Mario Heyer. He is aware of this and can connect us if you prefer.

**Comment by ToddKopriva** [comment]
> Hi @ToddKopriva, hope you are well. I am getting the following test errror:
> 
> `AssertionError [ERR_ASSERTION]: description should be of the form /^[a-zA-Z0-9\s.,\-()&#'"\/!]+\.$/.` but I do not see how my description does not match. Would you mind helping me out?
 
The description was missing the end punctuation. I fixed it.

**Comment by eblaauw** [comment]
Hey @ToddKopriva, I hope you are doing well.

Do you have any update on this? Can I help with anything?

**Comment by ToddKopriva** [comment]
> Do you have any update on this? Can I help with anything?

I'll be doing this review soon. Sorry for the delay. No, there's nothing that you need to do at this time.

**Comment by ToddKopriva** [comment]
@eblaauw , I'm sorry about the delay. Is this pull request still current? I'm ready to begin review on it, but I'm concerned that it might be outdated at this point. Just let me know, and I'll begin the review soon after I've received confirmation from you that you want to go forward with this PR and that it's up to date.

**Comment by eblaauw** [comment]
Hi @ToddKopriva, no worries! It is — but let me double check everything tomorrow and update where needed. I will confirm once that’s done.

**Comment by ToddKopriva** [comment]
Thanks.

**Comment by eblaauw** [comment]
@ToddKopriva It should be good to review now. I made a small change when it comes to how to set up an SSL from Cloudflare.

**Comment by ToddKopriva** [comment]
Thanks.

**Comment by ToddKopriva** [comment]
This publishing system is being shut down and is no longer accepting pull requests for new documents. Documents that have previously been published through this system are being moved to the `/archived` folder of this repository and are no longer being maintained.

**Pull request closed without merging**
