### PR TITLE
fixed bug where clamscan is used instead of clamdscan

### PR DESCRIPTION
**Pull request by AmsayIbbonsgay**
The container entrypoint is `start.py.`

This script creates a cronjob to  run `clamscan` every hour. 

`start.py `ends by executing `clamd`, which starts the clamd daemon. The daemon does nothing by itself, except load the virus database and wait for instructions. 

`clamdscan` sends instructions to the daemon to scan files. 
`clamscan` loads the virus database independently, and then sends instructions to scan files. It does not interact with the clamd daemon. 

https://www.clamav.net/documents/scanning
> Unlike clamdscan, clamscan does not require a running clamd instance to function. Instead, clamscan will create a new engine and load in the virus database each time it is run. It will then scan the files and/or directories specified at the command line, create a scan report, and exit.

It is redundant to start the engine with clamd and then use clamscan instead of clamdscan - this change will half the memory footprint of the container.

### CODE REVIEW

**Comment by ToddKopriva** [comment]
@ianmaddox , would you have a look at this proposed fix for a script that you contributed?

**Comment by AmsayIbbonsgay** [comment]
@googlebot I signed it!

**Comment by ToddKopriva** [comment]
Thanks, @AmsayIbbonsgay . I'll wait for @ianmaddox to confirm the fix, and then I'll merge it.

**Review by ianmaddox — COMMENTED** [review]
Thank you for the PR!
Diving into the code, the daemon is serving a purpose albeit a dumb one: To act as a canary for the healthcheck script `health.sh`. However, the resources consumed by the daemon is wasteful and can be optimized. I see a couple paths to streamline this architecture.

Stick with clamscan:
Comment out the clamd line in start.py and rely on the clamscan cron job that is configured and working. `health.sh` would need to be reworked to check for the freshclam process.

Switch to clamdscan:
In addition to the change you submitted, we need to remove the moot flags and add --multiscan. Then `clamd.conf` would need to be updated to include the following:
* the --exclude paths
* Add `LogSyslog yes`
* larger recursion cap
* Explicitly define verbosity to no
* explicit MaxThreads declaration (default value is OK, but this will be a hot item to reconfigure considering the container environment)

Like yourself, I'm leaning toward the clamdscan approach primarily for the tunable multiscan benefits. In the process of testing all this out, I've generated the diff that applies these fixes, so if you don't mind I'll close this PR and submit another one with all those changes plus a few others.

**Comment by ianmaddox** [comment]
Created #1598 with the requested fixes. This PR can be closed.

**Comment by ToddKopriva** [comment]
Thanks, @ianmaddox . And thanks again @AmsayIbbonsgay for pointing us in the right direction.

**Pull request closed without merging**
