### PR TITLE
Updates symfony GAE tutorial for symfony-demo 1.5

### PR DESCRIPTION
**Pull request by bshaffer**
- Updates the tutorial for the latest version of symfony and the latest symfony demo application
 - Adds changes from https://github.com/GoogleCloudPlatform/php-docs-samples/commit/3d4a2b9acfecd139e110875d0e364a2df7d640de by @Sethbass for integrating a mailer

### CODE REVIEW

**Comment by bshaffer** [comment]
See also https://github.com/GoogleCloudPlatform/php-docs-samples/pull/1034 and https://github.com/GoogleCloudPlatform/php-docs-samples/pull/1033

**Comment by ToddKopriva** [comment]
There are a couple of other items in the review queue ahead of this, so I'm estimating reviewing this on Friday.

**Comment by bshaffer** [comment]
Sounds good, thanks for the update @ToddKopriva

**Comment by Sethbass** [comment]
Thanks a lot @bshaffer  and @ToddKopriva  :) I have 2 other tutorials that I would like to add : 
* Session issue and usage of PDOSessionHandler
* File Upload

Should I continue on the same READ ME or do you think we should organise things differently ? Because I still expect a tutorial for MemoryStore (Redis) :)

**Comment by bshaffer** [comment]
Hey @Sethbass!
This is awesome to hear, we'd love to publish your contributions! I'd prefer keeping it single-page so it's all in one place. If it gets too big, we can split it out at any point.

**Comment by ToddKopriva** [comment]
I agree with @bshaffer .

**Pull request merged**
