### PR TITLE
New Tutorial: Kotlin Spring Boot on Google Compute Engine

### PR DESCRIPTION
**Pull request by hhariri**
- [x] Tech writing / styleguide review - @ryanmcginnis 
- [x] Formatting review for publishing - @jmdobry

### CODE REVIEW

**Comment by ryanmcginnis** [comment]
@hhariri, here is the [style guide](https://cloud.google.com/community/tutorials/styleguide) for GCP Community content.

**Comment by ryanmcginnis** [comment]
This LGTM, but let me know if another review pass is desired.

**Comment by hhariri** [comment]
Do I need to do something from my side on this?

**Comment by ryanmcginnis** [comment]
@jmdobry, this has been reviewed. Good to good?

**Comment by jmdobry** [comment]
Someone checked the box next to my name, but I haven't reviewed yet. Will do so now...

**Comment by hhariri** [comment]
@jmdobry sorry Jason that may have been me. Apologies

**Pull request merged**
