### PR TITLE
New hands-on tutorial

### PR DESCRIPTION
**Pull request by bernieongewe**

### CODE REVIEW

**Comment by bernieongewe** [comment]
Covered by Googler CLA

**Comment by bernieongewe** [comment]
Not yet.

I submitted this at the request of viglesias@ when he took a look at the
source material.

Cheers
Bernie (bernieongewe@)

**Comment by ToddKopriva** [comment]
I added Vic for a review. 

Vic, I'm just looking for a technical LGTM. I'll handle the editorial and production review.

If you'd rather tag someone else in for the review, that's fine, of course.

**Comment by viglesiasce** [comment]
The content looks solid. The only thing I would add is another diagram for Lab 2 and Lab 3.

**Comment by ToddKopriva** [comment]
Thanks, Vic.

**Comment by bernieongewe** [comment]
Will do. On this ASAP

**Comment by bernieongewe** [comment]
Updated

> Add diagrams for the second and third labs.

Added diagrams for the two labs

**Pull request merged**
