### PR TITLE
New Tutorial: Google Cloud VPN Interop Guide for Alibaba Cloud VPN Ga…

### PR DESCRIPTION
**Pull request by epluscloudservices**
This is a new tutorial for the Google Cloud VPN Interop Guide for Alibaba Cloud VPN Gateway.

### CODE REVIEW

**Comment by epluscloudservices** [comment]
We are working with the ePlus contracts team to get the CLA through for this account.

**Comment by epluscloudservices** [comment]
I signed it!

**Comment by JayLoomis** [comment]
The numbered lists aren't rendering correctly throughout the doc. Otherwise looks good to me.

**Comment by epluscloudservices** [comment]
For some reason the PR is still showing "Needs a CLA for the pull request sender". 
The CLA was signed and a comment of "I signed it" was commented here 9 days ago. Is there anything else I need to do?

**Comment by ToddKopriva** [comment]
I'll look into what is happening with the CLA.

**Comment by epluscloudservices** [comment]
Please let us know if there's anything we need to do on our side.

**Comment by ToddKopriva** [comment]
ePlus has signed a corporate CLA, and the author of this commit is a member of the ePlus group covered by that CLA.

**Comment by ToddKopriva** [comment]
David and I talked and decided to just create a new PR, rather than try to untangle this mess.

Here is the new PR:
https://github.com/GoogleCloudPlatform/community/pull/594

I'm closing this PR (#563).

**Pull request closed without merging**
