### PR TITLE
update index.md

### PR DESCRIPTION
**Pull request by tameto**
It is now changed to .gcloudignore

### CODE REVIEW

**Comment by bshaffer** [comment]
If we make this update, we need to add an example `.gcloudignore` with `.env` ignored to the tutorial as well.

Can you update your PR with this change?

**Comment by tameto** [comment]
@bshaffer 
I can do UPDATE.
Wait a while.

**Comment by ToddKopriva** [comment]
@tameto , are you still intending to make this change?

**Comment by ToddKopriva** [comment]
@tameto , it has been a few months since @bshaffer requested changes to this PR.

I'm going to close this PR now. If you want to continue with the update, feel free to re-open the PR.

**Pull request closed without merging**
