### PR TITLE
Added HBase monitoring for Dataproc cluster with HBase

### PR DESCRIPTION
**Pull request by NuwanSameera**

### CODE REVIEW

**Comment by NuwanSameera** [comment]
@ToddKopriva Changers are completed and CLA signed.

**Comment by NuwanSameera** [comment]
Any update ?

**Comment by NuwanSameera** [comment]
@ToddKopriva Any update

**Comment by ToddKopriva** [comment]
This publishing system is being shut down and is no longer accepting pull requests for new documents. Documents that have previously been published through this system are being moved to the `/archived` folder of this repository and are no longer being maintained.

**Pull request closed without merging**
