### PR TITLE
Changed docker file to pull in node:10 image

### PR DESCRIPTION
**Pull request by oliverbevan**

### CODE REVIEW

**Review by ToddKopriva — APPROVED** [review]

**Comment by ToddKopriva** [comment]
Thanks for the fix. Before we can merge the fix, we just need you to sign the CLA as the google-cla bot says above.

**Comment by oliverbevan** [comment]
@googlebot I signed it!

**Comment by oliverbevan** [comment]
I will redo this PR, looks like I had a different email address in my git config.

**Comment by ToddKopriva** [comment]
> I will redo this PR, looks like I had a different email address in my git config.

OK. Sorry for the hassle. Thanks again.

**Comment by oliverbevan** [comment]
https://github.com/GoogleCloudPlatform/community/pull/1825

**Pull request closed without merging**
