### PR TITLE
Simplify VM firewall rule setup

### PR DESCRIPTION
**Pull request by arunoo**
If we specify the built-in tag "https-server" then step 2 can be removed.

### CODE REVIEW

**Comment by arunoo** [comment]
Re CLA: I've whitelisted my google ldap. Please let me know if I need to do something more.

**Comment by tswast** [comment]
We should add a pointer to some docs that describe the default firewall rules and how they look for these tags.

**Comment by jmdobry** [comment]
@tswast Is this change good or does it need attention?

**Comment by tswast** [comment]
@jmdobry I'm not seeing the `http-server` tag documented at https://cloud.google.com/vpc/docs/firewalls#default_firewall_rules so I'm wary about accepting this change.

**Comment by jmdobry** [comment]
I found `https-server` in the docs, and even see it in use in some of my projects. Should be okay.

**Pull request merged**
