### PR TITLE
Deploy Grails App To Google Cloud Tutorial

### PR DESCRIPTION
**Pull request by sdelamo**

### CODE REVIEW

**Comment by sdelamo** [comment]
I signed it!

**Comment by steveperry-53** [comment]
@sdelamo, Thanks for putting this together.

Please make a pass through the topic to bring it into closer alignment with the [style guide](https://cloud.google.com/community/tutorials/styleguide). In particular, the style guide recommends that you:

* Use present tense.
* Address the reader as "you."
* Avoid saying "we."

Check for consistency in the way you use periods and colons.

Check for broken links.

Check for repeated content. For example, "Enable Cloud Storage API."

Make sure your triple backtick sections are rendering correctly. For example:

```configurations {
 +    compile.exclude module: "tomcat-juli"
 +    compile.exclude module: "spring-boot-starter-tomcat"
 +    compile.exclude(group: "com.google.guava", module: "guava-jdk5")
 +}```

Consider reducing the number of screenshots. I don't think you need so many screenshots of the console.

I think it would be better not to break the flow with too many alternatives. For example, I think it would be better if you didn't do this:

"or you can go right to the completed example:"
...
"Although you can go right to the completed example, in order to deploy the app you would need to complete several configuration steps in Google Cloud:"

Thanks again. Cheers,
Steve

**Comment by sdelamo** [comment]
Hello Steve, 

I believe I have addressed all the changes you requested. 

thanks,
Sergio

**Comment by steveperry-53** [comment]
@sdelamo, See https://github.com/GoogleCloudPlatform/community/pull/219/commits/89c1b8a70689931972aac7cdd2b4150a072b0a93 for suggested edits.

**Comment by steveperry-53** [comment]
@jmdobry, Can you figure out how to merge this? I'm stumped by the cla/google test.

**Comment by jmdobry** [comment]
@steveperry-53 Looks good to you?

**Comment by jmdobry** [comment]
It's not a problem, CLA is good, it just got confused after you and I added commits.

**Pull request merged**
