### PR TITLE
New Tutorial: Monitoring Google Cloud with InfluxDB Templates

### PR DESCRIPTION
**Pull request by gunnaraasen**
This is a tutorial on using InfluxDB templates and Telegraf to monitoring GCP resources in real-time using InfluxDB Cloud available in GCP Marketplace.

### CODE REVIEW

**Comment by ToddKopriva** [comment]
Thanks for the contribution, @gunnaraasen .

Before I get started on the review, we need you to sign the CLA as asked for by the bot in a previous comment.

**Comment by gunnaraasen** [comment]
@ToddKopriva I finally worked through the CLA bit. Let me know if anything else is needed to kick off a review!

**Comment by ToddKopriva** [comment]
Thanks, @gunnaraasen . There are a few other items in the queue, so I'll probably get to this review late Monday.

**Review by ToddKopriva — APPROVED** [review]

**Comment by ToddKopriva** [comment]
I'll publish this to cloud.google.com tomorrow with a batch of other changes.

Thanks again for the contribution.

**Comment by ToddKopriva** [comment]
published:
https://cloud.google.com/community/tutorials/influxdb-google-cloud-monitoring-templates

**Pull request merged**
