### PR TITLE
New Tutorial : Using app engine, angular, nginx, docker with single build for multiple environments

### PR DESCRIPTION
**Pull request by livesankp**
Adding these samples and tutorial to help community with google app engine, angular using custom flex environment of nginx and  using a single angular build for multi environment deployments in cloud

### CODE REVIEW

**Comment by livesankp** [comment]
@googlebot I signed it!

**Comment by livesankp** [comment]
Hello @ToddKopriva When possibly this can be reviewed? any ETA?

**Comment by livesankp** [comment]
Thanks @ToddKopriva Looking forward to it.

**Comment by livesankp** [comment]
@ToddKopriva I messed up this branch with my other github account and commits which was asking for CLA. Can you use this new PR instead of this and close this one ? https://github.com/GoogleCloudPlatform/community/pull/1728

**Comment by livesankp** [comment]
@googlebot I fixed it.

**Comment by livesankp** [comment]
@ToddKopriva I messed up this branch with my other github account and commits which was asking for CLA. Can you use this new PR instead of this and close this one ? https://github.com/GoogleCloudPlatform/community/pull/1728

**Comment by ToddKopriva** [comment]
> @ToddKopriva I messed up this branch with my other github account and commits which was asking for CLA. Can you use this new PR (#1728) instead of this and close this one ?

Sure. I can do that.

**Pull request closed without merging**
