### PR TITLE
New tutorial for Prestashop on GKE

### LINKED ISSUE #440: Tutorial request: Request for the Prestashop deployment on the GKE with Cloud SQL
Hello 

I would be helpful for the community to add tutorial for the open-source Prestashop on GKE with the Cloud SQL integration. 

References: https://github.com/PrestaShop/docker

### PR DESCRIPTION
**Pull request by gabihodoroaga**
Hi,

This is a new tutorial about how to deploy Prestashop on GKE
Fixes #440

### CODE REVIEW

**Comment by gabihodoroaga** [comment]
Hi

Do you have any news on the status of this PR?

Thanks
g.

**Comment by ToddKopriva** [comment]
> Hi
> 
> Do you have any news on the status of this PR?
> 
> Thanks
> g.

I'll be reviewing it this week.

**Review by ToddKopriva — APPROVED** [review]

**Comment by ToddKopriva** [comment]
@gabihodoroaga , thanks again for your contribution. I'll publish this with a batch of other changes tomorrow.

Sorry for the dealy on the review.

**Comment by gabihodoroaga** [comment]
@ToddKopriva , thank you for accepting the pull request and for review.

**Pull request merged**
