### PR TITLE
Pub/Sub Logging for pVM Shutdowns

### PR DESCRIPTION
**Pull request by mkahn5**
- [x] Tech writing / styleguide review - @dghale
- [x] Subject matter review - @jonparrott 
- [ ] Formatting review for publishing - @jmdobry

### CODE REVIEW

**Comment by jmdobry** [comment]
@jonparrott feel free to re-assign to another Python expert for subject matter review.

**Comment by jmdobry** [comment]
I'll do my review last.

**Comment by jmdobry** [comment]
@dghale After your edits, are you done with your review?

**Comment by dghale** [comment]
@jmdobry Yes. Review completed.

**Comment by jmdobry** [comment]
Can you please approve the PR?

**Comment by jmdobry** [comment]
Published: https://cloud.google.com/community/tutorials/pubsub-logging-pvm-shutdowns

**Pull request merged**
