### PR TITLE
New tutorial to show tokenization for CSV with row grouping and sorting

### PR DESCRIPTION
**Pull request by anantdamle**
This is a co-authored tutorial with @mrpaulthomas

### CODE REVIEW

**Comment by anantdamle** [comment]
@ToddKopriva Can you please look into this one, its been almost a Year!

**Comment by ToddKopriva** [comment]
> @ToddKopriva Can you please look into this one, its been almost a Year!

Yes. We are working through a large queue.

**Comment by anantdamle** [comment]
This solution is still current

**Comment by ToddKopriva** [comment]
This publishing system is being shut down and is no longer accepting pull requests for new documents. Documents that have previously been published through this system are being moved to the `/archived` folder of this repository and are no longer being maintained.

**Pull request closed without merging**
