### PR TITLE
New tutorial: Modular Load Balancing with Terraform

### PR DESCRIPTION
**Pull request by danisla**
New tutorial showing how to create various load balancing architectures with Terraform.

### CODE REVIEW

**Comment by danisla** [comment]
@JimTravis most of the edits look good to me but the code blocks need to be fixed. Changing to the indented notation loses the syntax highlighting. Is it ok to use the `'```language'` notation for syntax highlighting or does that break things?

**Comment by danisla** [comment]
Ok, is there a way to do syntax highlighting? If not, can you just remove the language (`sh`) from the indented block?

**Comment by danisla** [comment]
Is the migration of the images to the `https://storage.googleapis.com/gcp-community/tutorials` location done automatically? Do we need to do that beforehand and update the links in the `index.md` first?
Other than that, the changes LGTM.

**Comment by jmdobry** [comment]
Published: https://cloud.google.com/community/tutorials/modular-load-balancing-with-terraform

**Pull request merged**
