### PR TITLE
Fixes to make example work with Terraform v0.12.21

### PR DESCRIPTION
**Pull request by kucharskim**
I was going through this tutorial and examples didn't work. This pull request fixes the problem for me.

### CODE REVIEW

**Comment by kucharskim** [comment]
@googlebot I signed it!

**Comment by ToddKopriva** [comment]
@fawix , you have worked on fixes to this file recently. Could you have a look at this pull request?

**Comment by kucharskim** [comment]
@fawix I have another set of changes for `index.md` but I wanted to land those diffs here first. What exactly you want me to update?

**Comment by kucharskim** [comment]
Ok, I've pushed all my changes, including the part where I touch `index.md`. I went through few versions of making sure the dependency between `google_compute_instance` and `google_project_service.service` is captured. Have a look at the commits and let me know is the last version okay with you.

**Comment by fawix** [comment]
@kucharskim thanks! the `index.md` file actually has a copy and paste of the tf files that are mentioned during the explanation; that is what needs update. I will review your new commits

**Comment by kucharskim** [comment]
Oh, right! Then yeah, I need to update that too. I won't be able to do it in today, probably tomorrow.

**Comment by fawix** [comment]
@kucharskim thanks! I just finished reviewing the new commits and I think it's good to go; but I will wait for your `index.md` update with the `*.tf` files; 

btw, thanks for the PR! good catch :)

**Comment by kucharskim** [comment]
Ok, managed to do it just before logging off.

**Comment by fawix** [comment]
@ToddKopriva good to merge.

**Comment by ToddKopriva** [comment]
@kucharskim , thanks for the fix.

@fawix , thanks for the review.

I'll publish these changes to cloud.google.com with a set of other documents tomorrow.

**Comment by kucharskim** [comment]
Awesome! Thank you both, @fawix and @ToddKopriva!

**Comment by fawix** [comment]
@kucharskim thank you for the PR!

@ToddKopriva np, anytime! :)

**Pull request merged**
