### PR TITLE
proposed automl tables model export tutorial

### PR DESCRIPTION
**Pull request by amygdala**
This was originally conceived as a GCP blog post, but the editors thought it was a bit too long for a post, and suggested it might be a good fit here.  What do you think?  (It could also be turned into a 'solution', but I think it's a good fit for the community tutorials).

I've not done one of these before, so LMK if I goofed up anywhere.

### CODE REVIEW

**Comment by ToddKopriva** [comment]
I'll have a look soon. There are a few other items ahead of this in the queue, so it will be a few days.

**Comment by ToddKopriva** [comment]
Sorry for the delay on the review. I'm beginning the editing and production review now.

**Comment by amygdala** [comment]
hi Todd, just checking as to whether there's anything else I should do at the moment.

**Comment by ToddKopriva** [comment]
No. Sorry for the delay, Amy. Some other things leapt the priority queue. I'll get back to this this week.

**Comment by ToddKopriva** [comment]
https://cloud.google.com/community/tutorials/automl-tables-model-export

**Pull request merged**
