### PR TITLE
Running Partial Redaction of Credit Card Images with Google Cloud Functions and Data Loss Prevention API

### PR DESCRIPTION
**Pull request by arieljassan**
This tutorial describes how to partially redact images containing credit card numbers using a Cloud Function (GCF) written in Python 3.7 and Cloud Data Loss Prevention (DLP) API. The Cloud Function will be triggered in the event of an image object uploaded to a Cloud Storage (GCS) bucket.

In many cases, companies need to store images of the credit cards provided by their customers as proof of their purchase, and to comply with certifications such as PCI, they are required to redact part of the image to avoid visualizing the full number.

Data Loss Prevention API provides scalable classification and redaction for sensitive data elements like credit card numbers, and as of today, the API redacts credit card numbers fully. This is useful in most cases, but in others, for the image of the credit card to be useful it is necessary to have part of its number redacted while another part not redacted.

There might be cases in which the uploaded images do not contain credit card numbers or they are not clear enough. This solution includes instructions to set up GCS buckets for both, redacted and not redacted images, where the images will be stored after having been processed by the DLP API. Such implementation allows for setting different permissions levels and having more granular access control to each bucket.

### CODE REVIEW

**Comment by ToddKopriva** [comment]
@arieljassan , I think that you may have included an extra file by mistake. This file doesn't seem to be part of your new tutorial:
tutorials/standalone-tensorflow-raspberry-pi/index.md

Could you resolve that? 

I'll do the review on this tutorial next week.

**Comment by arieljassan** [comment]
Hi @ToddKopriva 
I've resolved the conflicts with the extra file.
Thanks.

**Comment by ToddKopriva** [comment]
Thanks, Ariel.

**Comment by arieljassan** [comment]
Hi Todd,
I've uploaded a new image under /images/credit-card2.png that I modified based on the following image: https://commons.wikimedia.org/wiki/File:Credit-card-front.svg

**Comment by arieljassan** [comment]
I've also make a correction to the import instruction in line 14

**Comment by ToddKopriva** [comment]
The new credit card image should work much better. Thanks.

I think that you need to update the index.md file slightly to accommodate the new file name.

Also, please remove the other image file from the PR.

**Comment by arieljassan** [comment]
Hi Todd, Thanks for noticing that. I've deleted the previous image (credit-card1.jpg) and updated the index.md file with the new image file name (credit-card2.png).
Please let me know if there is something else pending from me.

**Pull request merged**
