### PR TITLE
Tutorial for how to deploy dotnet core application using docker in gke and use ingress

### PR DESCRIPTION
**Pull request by livesankp**

### CODE REVIEW

**Comment by livesankp** [comment]
@ToddKopriva this lint failure is due to auto added file while creating dotnet project in Visual Studio Project templates. Is there a way to fix them ?

**Comment by ToddKopriva** [comment]
> @ToddKopriva this lint failure is due to auto added file while creating dotnet project in Visual Studio Project templates. Is there a way to fix them ?

I'll take a look when I review the PR.

**Comment by livesankp** [comment]
@ToddKopriva  I deleted those files which are not used in project so PR is good now. Please review when you can.

**Comment by ToddKopriva** [comment]
Thanks.

**Comment by livesankp** [comment]
@ToddKopriva When are you planning to review this?

**Comment by ToddKopriva** [comment]
> @ToddKopriva When are you planning to review this?

As soon as possible. We have a full work queue.

**Comment by livesankp** [comment]
@ToddKopriva can you review this?

**Comment by ToddKopriva** [comment]
> @ToddKopriva can you review this?

Yes, but it will still be a while. We're working through a large work queue.

**Comment by livesankp** [comment]
@ToddKopriva  any update this ?

**Comment by livesankp** [comment]
@ToddKopriva can you review this?

**Comment by ToddKopriva** [comment]
> @ToddKopriva can you review this?

Yes, I am just working through a big queue.

**Comment by ToddKopriva** [comment]
This publishing system is being shut down and is no longer accepting pull requests for new documents. Documents that have previously been published through this system are being moved to the `/archived` folder of this repository and are no longer being maintained.

**Pull request closed without merging**
