### PR TITLE
build: use GitHub Actions for CI

### PR DESCRIPTION
**Pull request by JustinBeckwith**
I'd like to stop paying for Circle CI, and this repo is one of the few remaining active repos :)

### CODE REVIEW

**Comment by ToddKopriva** [comment]
I'm OK with this change in principle, but I want @jmdobry to review this PR and give his thoughts.

**Comment by jmdobry** [comment]
GitHub Actions sounds great, I can't do it for a while though

**Comment by JustinBeckwith** [comment]
@jmdobry I kinda did it here .... are there other places that need to be touched to make this work?

**Review by jmdobry — APPROVED** [review]

**Comment by ToddKopriva** [comment]
What are the implications of this change for our publishing pipeline?

**Comment by jmdobry** [comment]
Just disregard the failing Circle CI checks. You should still be able to merge those PRs once approved (the new tests _are_ passing on those PRs). New PRs shouldn't have any failing CircleCI checks on them.

**Comment by JustinBeckwith** [comment]
I deleted the CircleCI webhook - shouldn't show up anymore :)

**Comment by ToddKopriva** [comment]
Thanks, @JustinBeckwith .

**Pull request merged**
