### PR TITLE
Add pomerium architecture diagram

### PR DESCRIPTION
**Pull request by travisgroth**

### CODE REVIEW

**Review by ahmetb — APPROVED** [review]

**Comment by ToddKopriva** [comment]
I uploaded the image file to the public storage bucket.

The text in the image looks fuzzy to me. @travisgroth , if it's good enough for you, I won't hold up the review, but I would recommend checking your output settings.

SVG files work well for this kind of diagram, too.

**Review by ToddKopriva — APPROVED** [review]
approving but not yet merging, in case @travisgroth wants to swap in an image with sharper text

**Comment by ahmetb** [comment]
I suspect Google Slides export functionality for PNG isn't that good. I recommend exporting as SVG, opening in browser, zooming in on a high-DPI display and cropping it.

**Comment by ToddKopriva** [comment]
Much better!

**Comment by travisgroth** [comment]
Thanks @ToddKopriva - that was originally slides -> svg -> gimp. 

I just used @ahmetb's trick, though I was probably just using gimp poorly.

**Pull request merged**
