### PR TITLE
appengine-angular-nginx-docker : Added flow diagram for better understanding

### PR DESCRIPTION
**Pull request by livesankp**
Added flow diagram for better understanding

### CODE REVIEW

**Comment by livesankp** [comment]
@ToddKopriva added flow diagram back. Please review.

**Comment by ToddKopriva** [comment]
> @ToddKopriva added flow diagram back. Please review.

I'll give you some copy-editing feedback in a little while, since I can't directly make the copy-edits in the image.

Also, the image must be uploaded as part of your pull request, not included by reference to an outside resource.

**Comment by livesankp** [comment]
> > @ToddKopriva added flow diagram back. Please review.
> 
> I'll give you some copy-editing feedback in a little while, since I can't directly make the copy-edits in the image.
> 
> Also, the image must be uploaded as part of your pull request, not included by reference to an outside resource.

I uploaded image and updated url.

**Review by ToddKopriva — COMMENTED** [review]
I appreciate the need to obscure some information in the app screenshot, but please do so with something other than the red scrawl that is currently used.

copy-editing for text in flow diagram:
- 'pre built' -> 'pre-built'
- Capitalize 'Angular'.

**Comment by livesankp** [comment]
> I appreciate the need to obscure some information in the app screenshot, but please do so with something other than the red scrawl that is currently used.
> 
> copy-editing for text in flow diagram:
> 
> * 'pre built' -> 'pre-built'
> * Capitalize 'Angular'.

@ToddKopriva I updated diagram.

**Review by ToddKopriva — APPROVED** [review]

**Comment by ToddKopriva** [comment]
Thanks. This change will be live when I publish a batch of changes within the next couple of days.

**Pull request merged**
