### PR TITLE
Update appengine-ruby-rails-activejob-pubsub.md

### PR DESCRIPTION
**Pull request by tracyloisel**
original gem activejob-google_cloud_pubsub is broken since the 1st of February 2019 because it uses a feature that has been removed from gem google-cloud-pubsub. So the tutorial could not work at all.

I fix it by forking the gem. @usmr author does not maintain anymore its gem, so i update this tutorial with my fork.

Since the 1st of February in 2019, gem google-cloud-pubsub has been updated (0.34.0 version) and it brokes compatibility with this current gem.

Extract from google-cloud-pubsub's changelog, 0.34.0 version :

Remove the #delay alias for modify_ack_deadline.
Users should use the modify_ack_deadline and modify_ack_deadline!
methods directly instead.

### CODE REVIEW

**Comment by tracyloisel** [comment]
@googlebot I signed it!

**Comment by ToddKopriva** [comment]
Thanks for the submission. I'll review this soon.

**Comment by ToddKopriva** [comment]
I have asked @chingor13 to look at this PR, since he worked on the original verison of the document.

**Comment by chingor13** [comment]
@tracyloisel We still don't have a record of the signed CLA. Before we can accept the PR, you'll need to make sure that you followed the above link and signed with the same email address used to make the commit.

**Comment by tracyloisel** [comment]
Ok i can rename the gem.

As a co founder and speaker at the Paris ruby on rails community, I met
many devs struggling with pubsub only because they're facing this issue
with activejob.

**Comment by chingor13** [comment]
I believe there are also ways to be added as an owner/take over ownership
of an unmaintained gem, but maybe that process is no longer viable (sorry,
I'm out of the loop).

**Comment by dazuma** [comment]
Yes, I'm really hesitant to point people at a github repo (especially at HEAD) rather than an actual released gem, in a tutorial. So that means either taking over ownership of the existing gem, or rereleasing it under a different name. @tracyloisel If you're willing to take over maintainership of the gem and release a fix, please feel free to pursue either option. Generally, taking over ownership is easiest if you can contact the original owner. If that's not feasible, it becomes a lot harder. You can contact RubyCentral and they _can_ transfer ownership but they'll need to make a good faith attempt to contact the original owner first, so it may take a long time. So if that's the case, rereleasing under a different name might be the better option.

**Comment by ToddKopriva** [comment]
@tracyloisel , do you intend to move forward with this pull request? I hope that the feedback from Jeff and Daniel has been useful.

**Comment by tracyloisel** [comment]
Sorry i did not reply.

I sent an email to try get to the ownership but nothing for the moment.

I will create a gem named Homework this weekend and I will keep you update.

Thank you guys, wish you a happy TGIF !!



Le jeu. 17 oct. 2019 à 16:53, Todd Kopriva <notifications@github.com> a
écrit :

**Comment by ToddKopriva** [comment]
Thanks for the update.

**Comment by ToddKopriva** [comment]
@tracyloisel , do you intend to go forward with this change?

**Comment by ToddKopriva** [comment]
@tracyloisel , are you still intending to work on this change? 

If not, or if you are uncertain, let's log this as an issue/bug against the tutorial and then close this current pull request. OK?

**Comment by ToddKopriva** [comment]
I'm closing this pull request because there hasn't been any activity for many months.

I am also moving the tutorial to the archived folder, since it is not working correctly in its current state and is not getting much traffic.

@tracyloisel , thank you very much for your attempt here and for calling our attention to this problem.

**Pull request closed without merging**
