### PR TITLE
Add SFTP to GCS Tutorial

### PR DESCRIPTION
**Pull request by elatovg**

### CODE REVIEW

**Comment by elatovg** [comment]
@ToddKopriva what is the best way to find a reviewer for this?

**Comment by ToddKopriva** [comment]
> @ToddKopriva what is the best way to find a reviewer for this?

This will be reviewed when we've gotten through some other items in our work queue.

**Comment by elatovg** [comment]
> > @ToddKopriva what is the best way to find a reviewer for this?
> 
> This will be reviewed when we've gotten through some other items in our work queue.

any new updates?

**Comment by ToddKopriva** [comment]
This publishing system is being shut down and is no longer accepting pull requests for new documents. Documents that have previously been published through this system are being moved to the `/archived` folder of this repository and are no longer being maintained.

**Pull request closed without merging**
