### PR TITLE
Add tutorials/cloud-tpu-with-shared-vpc-quickstart/index.md 

### PR DESCRIPTION
**Pull request by bernieongewe**
Basic TPU quickstart at https://cloud.google.com/tpu/docs/quickstart doesn't accommodate shared VPC

### CODE REVIEW

**Comment by ToddKopriva** [comment]
@bernieongewe , could you restart this pull request from a clean branch that doesn't include other files from your previous documents?

**Comment by bernieongewe** [comment]
Removed old file from the pull request

**Comment by ToddKopriva** [comment]
@bernieongewe , this is ready, except that the extraneous file is still part of the pull request. If you can't resolve this on your end, I'll just create a new pull request with the new file and merge that.

**Comment by bernieongewe** [comment]
> @bernieongewe , this is ready, except that the extraneous file is still part of the pull request. If you can't resolve this on your end, I'll just create a new pull request with the new file and merge that.

Sure. A new pull request is fine

**Pull request closed without merging**
