### PR TITLE
New Tutorial : Using app engine, angular, nginx, docker with single build for multiple environments

### PR DESCRIPTION
**Pull request by livesankp**

### CODE REVIEW

**Comment by livesankp** [comment]
@ToddKopriva this PR should be good to go now. Please do review on this one.

**Comment by ToddKopriva** [comment]
> @ToddKopriva this PR should be good to go now. Please do review on this one.

Will do.

**Review by ToddKopriva — APPROVED** [review]

**Comment by ToddKopriva** [comment]
Thanks for the contribution. I'll publish this with a batch of other changes either tomorrow or late today.

**Comment by livesankp** [comment]
Thanks @ToddKopriva Looking forward to it. I have one question though. Have you removed the diagram I have added ?

**Comment by ToddKopriva** [comment]
> Thanks @ToddKopriva Looking forward to it. I have one question though. Have you removed the diagram I have added ?

I did. We often don't include diagrams, and this one had some issues. If you want to put a diagram in in a follow-on pull request, we can get those issues addressed.

**Pull request merged**
