### PR TITLE
Community Tutorial: inspect BigQuery with DLP at scale with Dataflow and integrate with Data Catalog

### PR DESCRIPTION
**Pull request by mesmacosta**
This tutorial contains code written in Java and describes how to inspect BigQuery data at scale using Cloud Dataflow and Cloud Data Loss Prevention (DLP) API. Then Cloud Data Catalog API is used to create tags at column level with the sensitive elements found.

### CODE REVIEW

**Comment by mesmacosta** [comment]
@ToddKopriva could you take a look at this? Thanks :)

**Comment by ToddKopriva** [comment]
Will do. There are a few other items in the queue, so I'll probably review this on Wednesday.

**Comment by mesmacosta** [comment]
@ToddKopriva any updates on this? Thanks

**Comment by ToddKopriva** [comment]
> @ToddKopriva any updates on this? Thanks

Sorry for the delay. We should be able to publish this tomorrow or Wednesday.

**Review by ToddKopriva — APPROVED** [review]

**Pull request merged**
