### PR TITLE
New Tutorial: Automate Building Android APKs with Google Cloud Build CI/CD and a Gradle Docker Image

### PR DESCRIPTION
**Pull request by Timtech4u**
In this tutorial, you would setup a Cloud Build trigger that builds your android application and uploads it to a Cloud Storage Bucket.
The builds of new APK bundle would also be automatically triggered once code is pushed code to your code repository.

### CODE REVIEW

**Comment by Timtech4u** [comment]
Hi @ToddKopriva , I'm happy to write my second tutorial on Google Community Tutorials :-D

**Comment by ToddKopriva** [comment]
Thanks, Timothy.

I'll review this sometime this week.

**Comment by Timtech4u** [comment]
> Thanks, Timothy.
> 
> I'll review this sometime this week.

Thanks @ToddKopriva , that's fine by me.

**Comment by Timtech4u** [comment]
> Thanks, Timothy.
> 
> I'll review this sometime this week.

Soft reminder on this.

**Comment by ToddKopriva** [comment]
Yes, when I said that I would review this sometime this week, that was meant to indicate the possibility of late in the week.

**Comment by Timtech4u** [comment]
> Yes, when I said that I would review this sometime this week, that was meant to indicate the possibility of late in the week.

That's fine by me @ToddKopriva , thank you.

**Comment by Timtech4u** [comment]
> Timothy, while doing my editing pass and review, I hit some problems with the "Set up the Cloud Storage" section. While attempting to follow the instructions as written, I found that there wasn't quite enough information for me to follow the steps.
> 
> Please step through the procedure for setting up the Cloud Storage bucket, and make sure that the steps accurately and completely tell the user what they need to do for this part of the tutorial.
> 
> As soon as you have done that, I'll get back to reviewing and editing the document.
> 
> I greatly appreciate the work that you've done on this so far. I think that this will be a valuable resource when it is done.

Thanks @ToddKopriva , I would update this section and get back to you.

**Comment by Timtech4u** [comment]
Hi @ToddKopriva , does it seem better now.
I tried improving on the numbering list.

**Comment by ToddKopriva** [comment]
Thanks. I'll get back to the review soon, probably tomorrow.

**Comment by Timtech4u** [comment]
> Thanks, Timothy.
> 
> I finished my editing and production pass. I'll be publishing this with a batch of other documents within a couple of days.

Great job @ToddKopriva , thank you!

**Pull request merged**
