### PR TITLE
mosquitto >=2.0.0 have stricter security settings by default

### PR DESCRIPTION
**Pull request by barrowsr**
to use the tutorial as described the mosquitto configuration needed to be made less secure

### CODE REVIEW

**Comment by ToddKopriva** [comment]
@ptone , could you review this proposed change to some code that you contributed?

**Comment by ptone** [comment]
@barrowsr thanks for your contribution, can you provide any more context from some mosquitto release notes. I haven't tracked the project, do they now require auth by default? Are they now binding to 127.0.0.1 by default, but were implicitly binding to 0.0.0.0 before?

**Comment by barrowsr** [comment]
Yes it does seem that they were implicitly binding to 0.0.0.0 and are now using 127.0.0.1 by default.

[Announcement on mosquitto web site](https://mosquitto.org/blog/2020/12/version-2-0-0-released/)

> When the Mosquitto broker is run without configuring any listeners it will now bind to the loopback interfaces 127.0.0.1 and/or ::1. This means that only connections from the local host will be possible.

> All listeners now default to allow_anonymous false unless explicitly set to true in the configuration file. This means that when configuring a listener the user must either configure an authentication and access control method, or set allow_anonymous true

So it seems that by default the mosquitto server will only accept incoming connections from localhost on 1883 and those connections would need to have passwords setup. With the two config changes I provided it will enable anonymous login again (so no password required) and allow remote connections again.

It may be possible to use `listener 1883` instead of `bind_address 0.0.0.0` and get the same result:

> Running the broker with a listener defined will bind by default to 0.0.0.0 / :: and so will be accessible from any interface. It is still possible to bind to a specific address/interface.

But I have not tested that.

Please let me know if there is anything else I can provide.

**Comment by ptone** [comment]
Thanks for the provided context, that all makes sense. I see you have pushed some other changes - as it looks like you are actively iterating getting this to a better working state - do you want some more time to get everything stable and tested?

**Comment by barrowsr** [comment]
Sorry about that it is back to what it was supposed to be. 


I do have a branch working that uses TLS for the connections from clients to the bridge.  Is that something you would be interested in me doing another pull request for?

**Review by ToddKopriva — APPROVED** [review]

**Comment by ToddKopriva** [comment]
@ptone , is this OK to merge?

**Comment by ptone** [comment]
Thanks for this work @barrowsr , yes @ToddKopriva LGTM

**Comment by ToddKopriva** [comment]
Thanks to you both.

**Pull request merged**
