### PR TITLE
Add tutorial on callable cloud functions

### PR DESCRIPTION
**Pull request by samtstern**
At the request of some engineers working on the Cloud Translation API and the PM of Firebase Build I put together a tutorial; which shows how to safely call Cloud APIs directly from your mobile app using Cloud Functions and Firebase Authentication.

I tested this end-to-end using a completely new Cloud project and was able to complete it all successfully as written.

### CODE REVIEW

**Comment by samtstern** [comment]
cc @nauthadr

**Comment by ToddKopriva** [comment]
Thanks, @samtstern . Given what's in the queue right now, I'll probably begin review of this on Monday.

**Comment by samtstern** [comment]
@ToddKopriva thanks!  Sounds like a reasonable timeline to me.

**Review by ToddKopriva — APPROVED** [review]

**Comment by ToddKopriva** [comment]
I'll publish this to cloud.google.com tomorrow with a batch of other changes.

Thanks again for the contribution.

**Comment by samtstern** [comment]
@ToddKopriva thank you for the edits!

**Comment by ToddKopriva** [comment]
published:
https://cloud.google.com/community/tutorials/cloud-functions-callable

**Pull request merged**
