### PR TITLE
New tutorial: Deploy Dependency Track

### PR DESCRIPTION
**Pull request by dedickinson**
File location: tutorials/deploy-dependency-track

cc @glasnt as reviewer

### CODE REVIEW

**Comment by glasnt** [comment]
I have reviewed a draft version of this tutorial, and will review this submitted version ETA Monday, Australia time.

**Comment by glasnt** [comment]
Confirmed functionally sound.

**Comment by ToddKopriva** [comment]
> Confirmed functionally sound.

Thanks. I'll do the editorial review next.

**Comment by dedickinson** [comment]
Hi folks - thought I'd check in and see if there's anything you need me to do?

**Comment by ToddKopriva** [comment]
> Hi folks - thought I'd check in and see if there's anything you need me to do?

I'll be doing the editorial review of this in the next couple of days. Sorry for the delay.

**Comment by dedickinson** [comment]
My apologies but I thought I'd check in and see if there are any concerns.

**Comment by ToddKopriva** [comment]
> My apologies but I thought I'd check in and see if there are any concerns.

No concerns. We just had a large backlog of material to work through with I/O and some other projects. I'll be reviewing this this week.

**Review by ToddKopriva — APPROVED** [review]

**Comment by ToddKopriva** [comment]
published:
https://cloud.google.com/community/tutorials/deploy-dependency-track

Thanks for the contribution.

**Pull request merged**
