### PR TITLE
Add new tutorial:   bitmovin encoding product running on Google Cloud

### PR DESCRIPTION
**Pull request by Adrian-in-Aus**
This tutorial walks you through the process of installing bitmovin's video encoding product into Google Cloud.

### CODE REVIEW

**Comment by ToddKopriva** [comment]
@Adrian-in-Aus , thanks for the contribution.

As the google-cla bot says in a previous comment, we need you to sign the contributor license agreement before we can move forward.

The author field in the frontmatter is intended to be your GitHub username.

**Comment by Adrian-in-Aus** [comment]
@googlebot I signed it!   (corporate CLA)
Just to be sure, I filled all the details in again and was greeted with the error message "It looks like you've already signed this CLA."

**Comment by Adrian-in-Aus** [comment]
@googlebot I signed it! (corporate CLA)
Just to be sure, I filled all the details in again and was greeted with the error message "It looks like you've already signed this CLA." -   I think I see the issue,   my primary email address in github was not my work email.   This is now fixed.

**Comment by Adrian-in-Aus** [comment]
Thanks for your comment:
>I do have some concern that some of the steps require the reader to contact, such as to get information about filter and port settings.
We'd prefer to leave that level of detail out of the public doc,  in nearly all cases we'd be providing the customer these specifics under separate cover. (FYI - we're a google partner and there's a few contacts on your side I can (somehow) DM you so you can across the full background to how the two org's have solutioned thus far.

**Comment by ToddKopriva** [comment]
> Thanks for your comment:
> 
> > I do have some concern that some of the steps require the reader to contact, such as to get information about filter and port settings.
> 
> We'd prefer to leave that level of detail out of the public doc, in nearly all cases we'd be providing the customer these specifics under separate cover. (FYI - we're a google partner and there's a few contacts on your side I can (somehow) DM you so you can be across the full background to how the two org's have solutioned thus far.

OK. We can leave it at the level of detail that you have there. Thanks for the response.

**Comment by ToddKopriva** [comment]
> @googlebot I signed it! (corporate CLA)
> Just to be sure, I filled all the details in again and was greeted with the error message "It looks like you've already signed this CLA." - I think I see the issue, my primary email address in github was not my work email. This is now fixed.

Thanks. I'll see if I can help to move this forward.

**Pull request merged**
