### PR TITLE
Add tutorial for running tf image classification saved model

### PR DESCRIPTION
**Pull request by harshithdwivedi**
This commit adds the tutorial for running AutoML Image classification model in a python setting.
The blog was originally published here: 
https://heartbeat.fritz.ai/using-google-cloud-automl-edge-image-classification-models-in-python-92f2885c767

cc: @andrewferlitsch 

Signed-off-by: Harshit Dwivedi <harshit@pitech.app>

### CODE REVIEW

**Comment by harshithdwivedi** [comment]
@googlebot I signed it!

**Comment by andrewferlitsch** [comment]
LGTM

**Comment by ToddKopriva** [comment]
Thanks, Andrew. I'll do an editing and production pass. There are a few items ahead of this in the queue, so I expect to get to this on Wednesday.

**Comment by ToddKopriva** [comment]
@harshithdwivedi , thank you very much for the contribution.

I'm merging the pull request now, and I'll publish the tutorial on cloud.google.com later this week with a batch of other publications.

**Comment by harshithdwivedi** [comment]
Thanks @toddkopriva!
I have some more tutorials around AutoML that I'll be sharing soon enough.

**Pull request merged**
