### PR TITLE
Replicate the tutorial previously made in the php doc sample repo

### PR DESCRIPTION
**Pull request by Sethbass**
I have replicated the changes previously made in the php-doc-sample repo as this will be the one and only source for tutorials

### CODE REVIEW

**Comment by Sethbass** [comment]
@googlebot I fixed it.

**Comment by ToddKopriva** [comment]
@bshaffer , can you give this a technical review?

I'll do an editorial and production review after you give your approval.

**Comment by bshaffer** [comment]
@Sethbass please correct the email in the commit to match the email you've configured for GitHub. See "Editing the author of past commits" here: https://www.git-tower.com/learn/git/faq/change-author-name-email

**Comment by Sethbass** [comment]
@bshaffer  this pull request is closed and I have created a new one.

**Comment by ToddKopriva** [comment]
For anyone else following along, pull request #1193  continues this work.

**Pull request closed without merging**
