### PR TITLE
Laravel ignition bug

### PR DESCRIPTION
**Pull request by kkls-mike**
Since Laravel 6 uses facade/ignition package instead of beyondcode/laravel-dump-server, that results in a bug described in this issue - 
https://github.com/GoogleCloudPlatform/php-docs-samples/issues/986

### CODE REVIEW

**Comment by ToddKopriva** [comment]
Thanks for the contribution. 

I'll review this pull request soon. In the meantime, please follow the instructions that the googlebot added in a previous comment about signing the contributor license agreement.

**Comment by ToddKopriva** [comment]
@bshaffer , could you review this proposed change for a document that you authored.

**Comment by ToddKopriva** [comment]
Thanks, @bshaffer .

@kkls-mike , the only thing left is for you to signing the contributor license agreement. See the instructions from the googlebot in a previous comment.

**Comment by kkls-mike** [comment]
Thank you all!

@googlebot I signed it!

чт, 26 груд. 2019 о 20:36 Todd Kopriva <notifications@github.com> пише:

**Comment by ToddKopriva** [comment]
Thanks again, @kkls-mike .

**Pull request merged**
