### PR TITLE
Solutions guide for Delivering Cloud Monitoring Notifications to Third-Party Services

### PR DESCRIPTION
**Pull request by aprill1**
I'm an open source intern on the Alert Manager team working on developing a solutions guide + sample code for Cloud customers to deliver cloud monitoring alerts to third-party services. Since the team is transitioning when my internship is over, we are ideally looking to publish this guide as soon as possible.

### CODE REVIEW

**Comment by ToddKopriva** [comment]
I'll take a look tomorrow morning, at which time I can estimate how long the review will take.

**Comment by ToddKopriva** [comment]
The CircleCI tests are failing because the document doesn't use the frontmatter that it needs. 

To see what you need to include at the top, see a published document, like this one:
https://github.com/GoogleCloudPlatform/community/edit/master/tutorials/embedded-c-getting-started/index.md

**Comment by aprill1** [comment]
> I'll take a look tomorrow morning, at which time I can estimate how long the review will take.

Thanks so much! I also added the source code for the project since I included code snippets in the tutorial. I wasn't sure whether or not to include all the files from my project repo, but I've done so for now.

**Comment by aprill1** [comment]
Can I not include spaces in the tags?

**Pull request merged**
