### PR TITLE
Gsutil compression same bucket

### PR DESCRIPTION
**Pull request by RahulDubey391**
Lint check updated

### CODE REVIEW

**Comment by RahulDubey391** [comment]
How do I put the lint & test for just a single markdown(.md) file?

**Comment by RahulDubey391** [comment]
Hi @ToddKopriva , this branch is finalized. You can review and merge it. Thanks alot.

**Comment by RahulDubey391** [comment]
Hi @ToddKopriva , can you please review this and update me?

**Comment by ToddKopriva** [comment]
This is in our queue, but it is a long queue because we have some other things that we're working on right now.

**Comment by RahulDubey391** [comment]
Hi @ToddKopriva , thanks for the update. No worries, take your time.

**Comment by RahulDubey391** [comment]
Hi @ToddKopriva , can you please approve and review it?

**Comment by RahulDubey391** [comment]
@ToddKopriva Hi, can you please review and merge the documentation?

**Comment by ToddKopriva** [comment]
This publishing system is being shut down and is no longer accepting pull requests for new documents. Documents that have previously been published through this system are being moved to the `/archived` folder of this repository and are no longer being maintained.

**Pull request closed without merging**
