### PR TITLE
Adds a quickstart for Go in App Engine.

### PR DESCRIPTION
**Pull request by jscud**
Creating an interactive version of the quickstart guide for using Go in Google App Engine. @jmdobry for additional context.

### CODE REVIEW

**Comment by ToddKopriva** [comment]
- [ ] editorial review: @ToddKopriva 
- [ ] final production review for publishing: @ToddKopriva

**Comment by jscud** [comment]
Changed the filename to be go-gae-quickstart (instead of underscores)

**Comment by jscud** [comment]
Thank you Todd. Sounds good, the triple backticks would be nice to be able to keep since we also include the code language. I imagine indented code blocks couldn't specify the language, and we use it for some features like adding a button to send commands to Cloud Shell when the code is labeled as "bash".

Stripping the HTML tags is fine. In fact, we rely on this behavior to offer text instructions that are visible in static pages generated from the Markdown. In other words, this content can include custom tags that are rendered by the custom renderer when the content appears in-console, with alternate content that appears when viewing on GitHub or the Community Tutorials pages.

**Comment by ToddKopriva** [comment]
I'll publish this soon, and we can come back and make tweaks if necessary.

**Pull request merged**
