### PR TITLE
New tutorial: Develop a Serverless Application with Vision API

### PR DESCRIPTION
**Pull request by glasnt**
Create a new multi-part tutorial, going from `gcloud` and client APIs, to a fully serverless hosted service to detect breeds of doggo in uploaded images 🐶

Self-tested, but I can also get a domain reviewer if that will help. 

Happy for a tutorial name/description change if the current version doesn't suit.

### CODE REVIEW

**Comment by glasnt** [comment]
Hi @ToddKopriva. I realise this has been sitting in the queue a while, and I'm wondering what I can do to help move it through. It's been a while so I can try running the tutorial myself in a new project, if that'll help with confirming it all works?

**Comment by ToddKopriva** [comment]
@glasnt , sorry for the delay. Is this pull request still current? I'm ready to begin review on it, but I'm concerned that it might be outdated at this point. Just let me know, and I'll begin the review soon after I've received confirmation from you that you want to go forward with this PR and that it's up to date.

**Comment by glasnt** [comment]
@ToddKopriva I've just run it through and made some small updates, but apart from some formatting and bumping the client lib versions, it runs through clean for me.

**Comment by ToddKopriva** [comment]
Thanks, @glasnt .

**Comment by glasnt** [comment]
Opting to move this to devrel-demos, https://github.com/GoogleCloudPlatform/devrel-demos/pull/53

**Pull request closed without merging**
