### PR TITLE
Connecting GKE workloads to services in different GCP Projects using Shared VPC tutorial

### PR DESCRIPTION
**Pull request by soeirosantos**
This tutorial is based on [a tutorial I wrote some time ago](https://todevornot.com/post/620549463290871808/shared-vpc-with-gke-and-cloud-memorystore) and thought could be suitable for the Google Cloud Community.

### CODE REVIEW

**Comment by soeirosantos** [comment]
@googlebot I signed it!

**Comment by ToddKopriva** [comment]
Thanks for the contribution. There are a few other items in the queue, so I will probably review this in the second half of this week.

**Review by ToddKopriva — APPROVED** [review]

**Comment by ToddKopriva** [comment]
Thanks again for the contribution, @soeirosantos . I'll publish this with a batch of other updates tomorrow.

**Comment by soeirosantos** [comment]
Thank you @ToddKopriva, for the review and adjustments.

**Comment by ToddKopriva** [comment]
> Thank you @ToddKopriva, for the review and adjustments.

Happy to help. This was an easy document to edit because of how well written it was. I just needed to adjust for our style a little.

**Comment by ToddKopriva** [comment]
published:
https://cloud.google.com/community/tutorials/shared-vpc-gke-cloud-memorystore

**Pull request merged**
