### PR TITLE
Bigtable + Memcached article

### PR DESCRIPTION
**Pull request by billyjacobson**

### CODE REVIEW

**Comment by ToddKopriva** [comment]
Thanks, @billyjacobson .

There is a template linked to from the contributor's guide here:
https://cloud.google.com/community/tutorials/write

That will help you past the lint issues and such.

**Comment by billyjacobson** [comment]
@ToddKopriva hey let me know if there's anything else I need to do for this, thanks!

**Comment by ToddKopriva** [comment]
Will do.

There are a few other items in the queue ahead of this, so it might be Monday before I get to the editorial and production review.

**Comment by billyjacobson** [comment]
@ToddKopriva just wanted to follow up on this, thanks!

**Comment by ToddKopriva** [comment]
I'll be reviewing it today.

**Review by ToddKopriva — APPROVED** [review]

**Comment by ToddKopriva** [comment]
published:
https://cloud.google.com/community/tutorials/bigtable-memcached

**Pull request merged**
