### PR TITLE
speech2srt: fix broken conversion

### PR DESCRIPTION
**Pull request by tmatth**
start_time and end_time are already datetime.timedeltas

Fixes:
> start = w.start_time.ToTimedelta()
> AttributeError: 'datetime.timedelta' object has no attribute 'ToTimedelta'

### CODE REVIEW

**Review by ToddKopriva — APPROVED** [review]

**Comment by ToddKopriva** [comment]
Thanks for that, @tmatth .

**Comment by bmalnersic** [comment]
Hm, this breaks the application on my WLS2/Ubuntu 22.04LTS/Python3.10 environment. I get an error: **TypeError: '<' not supported between instances of 'Duration' and 'Duration'**

`Transcribing gs://movie_audio/example.wav ...
Transcribing finished
Writing en-US subtitles to: subtitle.srt
Traceback (most recent call last):
  File "/home/blaz/src/community/tutorials/speech2srt/speech2srt.py", line 155, in <module>
    main()
  File "/home/blaz/src/community/tutorials/speech2srt/speech2srt.py", line 150, in main
    write_srt(args, subs)
  File "/home/blaz/src/community/tutorials/speech2srt/speech2srt.py", line 93, in write_srt
    f.writelines(srt.compose(subs))
  File "/home/blaz/src/community/tutorials/speech2srt/venv/lib/python3.10/site-packages/srt.py", line 411, in compose
    return "".join(subtitle.to_srt(strict=strict, eol=eol) for subtitle in subtitles)
  File "/home/blaz/src/community/tutorials/speech2srt/venv/lib/python3.10/site-packages/srt.py", line 411, in <genexpr>
    return "".join(subtitle.to_srt(strict=strict, eol=eol) for subtitle in subtitles)
  File "/home/blaz/src/community/tutorials/speech2srt/venv/lib/python3.10/site-packages/srt.py", line 264, in sort_and_reindex
    for sub_num, subtitle in enumerate(sorted(subtitles), start=start_index):
  File "/home/blaz/src/community/tutorials/speech2srt/venv/lib/python3.10/site-packages/srt.py", line 108, in __lt__
    return self.start < other.start or (
TypeError: '<' not supported between instances of 'Duration' and 'Duration'`
If I revert back to the original code (with conversion .ToTimedelta()) there is no issue.

**Comment by tmatth** [comment]
For reference, I'm testing with:
google-cloud-speech==2.16.2

**Comment by ToddKopriva** [comment]
@bmalnersic , interesting.
 This might be more conditional.

**Comment by bmalnersic** [comment]
Then the content of the _requirements.txt_ also needs to be updated, as the older versions of the libraries (google-cloud-speech==1.2.0 and srt==3.0.0) are explicitly required.

**Comment by tmatth** [comment]
> Then the content of the _requirements.txt_ also needs to be updated, as the older versions of the libraries (google-cloud-speech==1.2.0 and srt==3.0.0) are explicitly required.

Thanks I've addressed this here (I left the `srt` version as is as it didn't need an upgrade): https://github.com/GoogleCloudPlatform/community/pull/2263

**Pull request merged**
