### PR TITLE
Fix typo - security

### PR DESCRIPTION
**Pull request by awithey**
There is a simple typo in index.md. Security is misspelled as "Security".

### CODE REVIEW

**Comment by awithey** [comment]
I signed it!

**Comment by awithey** [comment]
I signed it!

**Comment by jmdobry** [comment]
@googlebot CLA looks good?

**Comment by jmdobry** [comment]
@awithey Does the email of your git commits match the email with which you signed the CLA?

**Comment by jmdobry** [comment]
PR now obsolete

**Pull request closed without merging**
