### PR TITLE
New tutorial: Routing traffic by JSON Web Token claims with Istio

### PR DESCRIPTION
**Pull request by halvards**
Peer reviewed draft.

### CODE REVIEW

**Comment by ToddKopriva** [comment]
Sorry for the delay on this Halvard. The review of this will be somewhat demanding, since it involves testing of the integration with the console and making sure that the tutorial works in all three locations (c.g.c, GitHub, console).

**Comment by ToddKopriva** [comment]
Sorry again for the delay, @halvards . Now that I've got the queue clear, I can begin to work on this. The first step will be for me to do some testing of this in the console context.

**Comment by ToddKopriva** [comment]
@halvards , is this pull request still current? I'm ready to begin review on it, but I'm concerned that it might be outdated at this point. Just let me know, and I'll begin the review soon after I've received confirmation from you that you want to go forward with this PR and that it's up to date. Sorry about the delay.

**Comment by halvards** [comment]
Thanks @ToddKopriva , I'll take a look and see what would be required to bring it up to date.

**Comment by ToddKopriva** [comment]
This publishing system is being shut down and is no longer accepting pull requests for new documents. Documents that have previously been published through this system are being moved to the `/archived` folder of this repository and are no longer being maintained.

**Pull request closed without merging**
