### PR TITLE
Add Azure mirroring tutorial

### PR DESCRIPTION
**Pull request by manokhina**
Tutorial for setting up an Azure Pipeline for mirroring the Azure repository into Cloud Source Repository.

### CODE REVIEW

**Review by Rohit484 — COMMENTED** [review]
here

**Review by thesmiler — APPROVED** [review]

**Comment by ToddKopriva** [comment]
Thanks, @smiler .

I will do the editorial and production review now.

**Review by ToddKopriva — APPROVED** [review]

**Comment by ToddKopriva** [comment]
Thanks again for the article, @manokhina . I'll publish this on Monday.

**Comment by ToddKopriva** [comment]
published:
https://cloud.google.com/community/tutorials/azure-mirroring-tutorial

**Pull request merged**
