### PR TITLE
Measuring BigQuery query performance with Google Colab

### PR DESCRIPTION
**Pull request by arieljassan**

### CODE REVIEW

**Comment by ToddKopriva** [comment]
@arieljassan , I'm sorry about the delay on this review. is this pull request still current? I'm ready to begin review on it, but I'm concerned that it might be outdated at this point. Just let me know, and I'll begin the review soon after I've received confirmation from you that you want to go forward with this PR and that it's up to date.

**Comment by arieljassan** [comment]
Hi Todd,
What do you mean with current? That's it's still relevant?

**Comment by ToddKopriva** [comment]
> Hi Todd, What do you mean with current? That's it's still relevant?

Yes, I'm just checking that it's still relevant and still correct (not outdated).

**Review by arieljassan — COMMENTED** [review]
Updated the Colab url.

**Comment by arieljassan** [comment]
Hi Todd, I've reviewed it and changed an outdated url.

**Comment by ToddKopriva** [comment]
Thanks.

**Comment by arieljassan** [comment]
Hello. Any news about this?

**Comment by ToddKopriva** [comment]
This publishing system is being shut down and is no longer accepting pull requests for new documents. Documents that have previously been published through this system are being moved to the `/archived` folder of this repository and are no longer being maintained.

**Pull request closed without merging**
