### PR TITLE
Run Spring Inventory Manager with Cloud SQL, Secret Manager on App Engine flexible environment using Cloud Build

### PR DESCRIPTION
**Pull request by kioie**
Tutorial discussing how to deploy Spring Inventory Manager Demo application to the App Engine flexible environment and use Cloud SQL, Secret Manager and Cloud Build.

### CODE REVIEW

**Comment by ToddKopriva** [comment]
Thanks for the submission. We're just returning from a long holiday weekend, so it may be a few days before this review is done.

**Comment by kioie** [comment]
> Thanks for the submission. We're just returning from a long holiday weekend, so it may be a few days before this review is done.

No worries, thanks for the heads up.

**Comment by kioie** [comment]
hey @ToddKopriva, was this reviewed?

**Comment by ToddKopriva** [comment]
It's in progress.

**Comment by kioie** [comment]
> It's in progress.

No worries...thanks!

**Comment by kioie** [comment]
Thanks for your review @ToddKopriva !

**Comment by ToddKopriva** [comment]
> Thanks for your review @ToddKopriva !

Thanks again for the contribution.

**Pull request merged**
