### PR TITLE
kafka cluster setup gce

### PR DESCRIPTION
**Pull request by rk-cloudside**
This is a tutorial for setting up a highly available Kafka cluster on Google Compute Engine

- Create VPC, subnet, firewall rules 
- Configure a Zookeeper esmble on GCE
- Configure Kafka brokers

### CODE REVIEW

**Review by ToddKopriva — CHANGES_REQUESTED** [review]
Please use an approved Google Cloud logo instead of the version of our mark that you have in the upper left corner of the architecture diagram.

You can get approved images here:
https://cloud.google.com/icons

**Comment by ToddKopriva** [comment]
I'll review this pull request after the image has been updated.

**Comment by rk-cloudside** [comment]
> I'll review this pull request after the image has been updated.

I have updated the architecture diagram

**Comment by rk-cloudside** [comment]
Hi @ToddKopriva - Anything else I need to do? I have updated the arch diagram with the approved logo.

**Comment by ToddKopriva** [comment]
> Hi @ToddKopriva - Anything else I need to do? I have updated the arch diagram with the approved logo.

I'll be reviewing this after I've gotten through other items in the queue. Sorry for the delay.

**Comment by ToddKopriva** [comment]
This publishing system is being shut down and is no longer accepting pull requests for new documents. Documents that have previously been published through this system are being moved to the `/archived` folder of this repository and are no longer being maintained.

**Pull request closed without merging**
