### PR TITLE
Ml pipeline example

### PR DESCRIPTION
**Pull request by enakai00**
Hi, I'd like to contribute to the community tutorial with my example. This tutorial explains how you can use Cloud Workflows and other serverless services, such as Cloud Run, to create a custom ML pipeline. (Note: I'm a googler.)

### CODE REVIEW

**Comment by ToddKopriva** [comment]
Has this received a technical review yet?

**Comment by enakai00** [comment]
I will ask a peer-review to my SA-peer hasebe@.

By the way, you can see the formatted content (including the architecture diagram) from [this link](https://github.com/enakai00/community/blob/peer-review/tutorials/ml-pipeline-with-workflows/index.md). (The link to the diagram in index.md in the pull-req points the upstream repo. So it doesn't show the diagram unless merged to the master.)

**Comment by ToddKopriva** [comment]
> I will ask a peer-review to my SA-peer hasebe@.

Great. Thanks.

**Comment by hasebe** [comment]
@ToddKopriva @enakai00 
LGTM.
Reviewed and confirmed that everything works fine.

**Comment by ToddKopriva** [comment]
Excellent. I'll pick up the editorial and production review within a few days.

**Comment by shivamkumar0611** [comment]
> I will ask a peer-review to my SA-peer hasebe@.
> 
> By the way, you can see the formatted content (including the architecture diagram) from [this link](https://github.com/enakai00/community/blob/peer-review/tutorials/ml-pipeline-with-workflows/index.md). (The link to the diagram in index.md in the pull-req points the upstream repo. So it doesn't show the diagram unless merged to the master.)

Thanks

**Review by shivamkumar0611 — APPROVED** [review]

**Review by shivamkumar0611 — APPROVED** [review]

**Comment by enakai00** [comment]
Hello, what's the status of this? Do I need to do something from my side?

**Comment by ToddKopriva** [comment]
> Hello, what's the status of this? Do I need to do something from my side?

It's in the queue. The holidays and other matters have caused this to take longer than expected.

**Review by ToddKopriva — APPROVED** [review]

**Comment by ToddKopriva** [comment]
published:
https://cloud.google.com/community/tutorials/ml-pipeline-with-workflows

**Comment by enakai00** [comment]
Thanks!

**Comment by ToddKopriva** [comment]
Thanks again for the contribution.

**Pull request merged**
