### PR TITLE
New community tutorial: Use Firebase and Cloud Run from React web application

### PR DESCRIPTION
**Pull request by enakai00**
Hi, I've created a new tutorial to learn about using Firebase and Cloud Run from React web application.

### CODE REVIEW

**Comment by enakai00** [comment]
@hasebe -san, can you give a SA peer review to this tutorial?

**Comment by hasebe** [comment]
@enakai00 -san,
SA peer review completed. I confirmed that I could proceed the tutorial without any errors on a fresh Google Cloud project.

**Comment by Guertovstoper** [comment]
👍

**Comment by ToddKopriva** [comment]
This publishing system is being shut down and is no longer accepting pull requests for new documents. Documents that have previously been published through this system are being moved to the `/archived` folder of this repository and are no longer being maintained.

**Pull request closed without merging**
