### PR TITLE
Restricting GKE Workload Identity with Kyverno

### PR DESCRIPTION
**Pull request by soeirosantos**
Hi, this is something I thought could be interesting to share with the Google Cloud Community.

I'm attaching the manifests files for reference only because the indentation in these heredocs can be tricky.

### CODE REVIEW

**Comment by soeirosantos** [comment]
Sorry for the late commits. I caught some minors when reviewing the PR myself - we are all set from my side. 

In time, I think the title of the tutorial could be improved to use the keywords policy or policy management. I'm open to suggestions.

**Comment by ToddKopriva** [comment]
Thanks for the contribution. There are some other items in the queue, so I'll probably do the editorial and production review on Thursday.

**Comment by shivamkumar0611** [comment]
> Thanks for the contribution. There are some other items in the queue, so I'll probably do the editorial and production review on Thursday.

okay..thanks : )

**Comment by soeirosantos** [comment]
Hi @ToddKopriva, just wanted to quickly follow up on this. Please, let me know if there is anything I can do to help the review.

**Comment by ToddKopriva** [comment]
> Hi @ToddKopriva, just wanted to quickly follow up on this. Please, let me know if there is anything I can do to help the review.

Nothing is needed right now. I just need to work through some other items. I will get to this later this week.

**Review by ToddKopriva — APPROVED** [review]

**Pull request merged**
