### PR TITLE
Patching Issue #1561

### PR DESCRIPTION
**Pull request by TheJaySmith**
https://github.com/GoogleCloudPlatform/community/issues/1561

fixed gcp-community/tutorials/secrets-manager-python/py-secrets-manager/currencyapp/app.py

### CODE REVIEW

**Comment by ToddKopriva** [comment]
Thanks for the pull request, @TheJaySmith . It looks like you accidentally pulled in some changes that aren't related to this fix.

**Comment by TheJaySmith** [comment]
I believe that I managed to remove the pulls that have nothing to do with secrets-manager. There is an update to the index.md

**Comment by TheJaySmith** [comment]
Files should be removed now.

**Review by ToddKopriva — APPROVED** [review]

**Comment by steve-kidreads-app** [comment]
Fix not reflected here: https://cloud.google.com/community/tutorials/secrets-manager-python#review_the_app_code

**Comment by ToddKopriva** [comment]
> Fix not reflected here: https://cloud.google.com/community/tutorials/secrets-manager-python#review_the_app_code

Ah, you're right. The file containing the code was fixed, but the snippet of the code in the document file wasn't updated. I created a new issue to address this.

**Pull request merged**
