### PR TITLE
Community Tutorial: inspect BigQuery with DLP and integrate with Data Catalog

### PR DESCRIPTION
**Pull request by mesmacosta**
This tutorial contains code written in Java and describes how to inspect BigQuery data using Cloud Data Loss Prevention (DLP) API. Then Cloud Data Catalog API is used to create tags at column level with the sensitive elements found.

### CODE REVIEW

**Comment by mesmacosta** [comment]
Any update on this?

Thanks

**Comment by ToddKopriva** [comment]
There are a few more items ahead of this in the review queue. We'll begin the review soon.

**Comment by mesmacosta** [comment]
sure thanks!

**Comment by mesmacosta** [comment]
any news? :)

**Comment by ToddKopriva** [comment]
I'll be starting this review late today.

**Comment by mesmacosta** [comment]
Thanks @ToddKopriva

**Comment by mesmacosta** [comment]
@ToddKopriva is there an ETA for the publication?

Thanks

**Comment by ToddKopriva** [comment]
this week

**Comment by ToddKopriva** [comment]
I'll publish this tomorrow morning.

**Pull request merged**
