### PR TITLE
Fixes lint

### PR DESCRIPTION
**Pull request by gguuss**

### CODE REVIEW

**Comment by gguuss** [comment]
@coisme, as far as I can tell, `event.data.data` will always be undefined which would break the sample. The issue this fixes is the lint issues in the Community samples checks, the sample was working as tested.

I just tested the code against PubSub and an IoT Core registry and it does not

**Comment by coisme** [comment]
Hi @gguuss, thank you for reply. Really... I tested your code and my code with PubSub and IoT core, too. Let me check it again.

**Comment by coisme** [comment]
Hi @gguuss, I tried again. `virtualdev.js` runs successfully but I observe an error in my log:
```
TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object. at fromObject (buffer.js:262:9) at Function.Buffer.from (buffer.js:101:10) at exports.relayCloudIot (/user_code/index.js:13:16) at /var/tmp/worker/worker.js:721:16 at /var/tmp/worker/worker.js:670:9 at _combinedTickCallback (internal/process/next_tick.js:73:7) at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

If I change the program as I suggested, this error disappears. I think this is consistent with an older version:
https://github.com/GoogleCloudPlatform/community/blob/a8082e72476063f8875739b45e0098835d1eea77/tutorials/iot-device-to-device/dev2dev/index.js#L57-L60

Could you try?

**Comment by gguuss** [comment]
Ahh, it's a node 6 vs node 8 issue!  I should add some instructions.

**Comment by gguuss** [comment]
@JayLoomis PTAL, I had to fix some minor lint issues and a reviewer noticed I also needed to specify node8

**Comment by gguuss** [comment]
@ptone can you approve, this fixes lint and some breaking changes in GCF

**Comment by JayLoomis** [comment]
No real language impact to your changes, so LGTM from my PoV.

**Comment by gguuss** [comment]
@JayLoomis can you approve the PR?  I'm still blocked from committing.

**Pull request merged**
