### PR TITLE
Adds tutorial for connecting FLedge (Dianomic FogLamp) to Cloud IoT Core

### PR DESCRIPTION
**Pull request by gguuss**

### CODE REVIEW

**Comment by gguuss** [comment]
@ashwinscale - Feel free to take a look and add anyone from the Dianomic side who you feel would be good to include here.

**Comment by ToddKopriva** [comment]
I'll do the editorial review of this document late this week.

@gguuss , are you already covered for technical review of this document?

**Comment by gguuss** [comment]
I'll try and think of someone for technical review, but I have reached out to the folks from Dianomic.

**Comment by billehunt** [comment]
This looks really good, Gus! Ashwin is testing all the steps.

**Comment by ashwinscale** [comment]
LGTM

**Comment by ToddKopriva** [comment]
Thanks for the review, @ashwinscale . I'll start the editorial review tomorrow.

**Pull request merged**
