### PR TITLE
Update workload tutorial's cluster create, kubectl delete commands

### PR DESCRIPTION
**Pull request by lbordowitz**
I've gone through the tutorial, except for the `Cloud Run Invoker IAM authorization` section. I've updated a couple of the commands here so that they work.

### CODE REVIEW

**Comment by ToddKopriva** [comment]
@ptone , could you have a look at this proposed update to a tutorial that you contributed?

**Comment by ptone** [comment]
LGTM - seems some of the flag terminology was changed after this first published.

**Comment by ToddKopriva** [comment]
> LGTM - seems some of the flag terminology was changed after this first published.

Thanks, @ptone . I'll merge this, then.

**Comment by ToddKopriva** [comment]
@lbordowitz , we just need you to sign the CLA before this can be merged.

**Comment by lbordowitz** [comment]
Had to force-push; when I auto-merged, the commits added to bring it in line with master had automated contributors which had not signed the CLA.

**Comment by ToddKopriva** [comment]
Thanks for the fix, @lbordowitz .

**Comment by ToddKopriva** [comment]
I'll publish this with a batch of other fixes at the end of this week.

**Pull request merged**
